export type TabType =
  | 'dashboard'
  | 'inventory'
  | 'employees'
  | 'licenses'
  | 'cloud'
  | 'procurement'
  | 'servicedesk'
  | 'device_service_requests'
  | 'vendors'
  | 'user_requests'
  | 'compliance'
  | 'verification'
  | 'ai_assistant'
  | 'analytics'
  | 'settings';
